version: '3.8'
services:
  api:
    container_name: library-api
    build:
      context: .
      target: development
    volumes:
      - .:/home/node/app
    command: pnpm start:dev
    ports:
      - '$SERVER_PORT:$SERVER_PORT'
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    container_name: library-db
    image: mysql
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    env_file: .env
