version: '3.8'
services:
  api:
    container_name: libraty-api
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    command: pnpm start:dev
    volumes:
      - .:/home/node/app
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql
    volumes:
      - ./data0:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    env_file: .env
